# Generated by Django 3.1.6 on 2021-02-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadfile',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('uploadlocation', models.FileField(upload_to='./upload')),
            ],
            options={
                'db_table': 'uploadfile',
            },
        ),
    ]
