# Generated by Django 3.1.6 on 2021-02-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='graphfile',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('graphlocation', models.CharField(max_length=256)),
                ('graphname', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'graphfile',
            },
        ),
    ]
