# Generated by Django 3.1.6 on 2021-03-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_graphdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileinfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('node_numbers', models.CharField(max_length=10)),
                ('edges_numbers', models.CharField(max_length=10)),
                ('anomalous_ndoes', models.CharField(max_length=10)),
                ('anomalous_edges', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'fileinfo',
            },
        ),
    ]
